// <auto-generated />
namespace OfferProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class requiredAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202208091419271_requiredAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
